### ISSUE TITLE
Tabs/spaces inconsistency

### ISSUE THREAD

**Issue by payet-s** [pasquim/apirate#3]
Most files have tabs/spaces inconsistency. Sometimes you even added additional spaces at the begin of each line.

See:
- [eMethod.h](https://github.com/pasquim/apirate/blob/master/Apirate/eMethod.h)
- [eModule.h](https://github.com/pasquim/apirate/blob/master/Apirate/eModule.h)
- [eQuery.h](https://github.com/pasquim/apirate/blob/master/Apirate/eQuery.h)
- [eLog.h](https://github.com/pasquim/apirate/blob/master/Apirate/eLog.h)
- [ISocket.h](https://github.com/pasquim/apirate/blob/master/Apirate/ISocket.h)
- [IResponse.h](https://github.com/pasquim/apirate/blob/master/Apirate/IResponse.h)
- [IRequest.h](https://github.com/pasquim/apirate/blob/master/Apirate/IRequest.h)
- [IQuery.h](https://github.com/pasquim/apirate/blob/master/Apirate/IQuery.h)

**Comment by pasquim** [comment]
Fixed by a commit.
https://github.com/pasquim/apirate/commit/1abf9ec33ad32281f876c429df7a512087b5be75
