### ISSUE TITLE
Source Code & UML mismatch

### ISSUE THREAD

**Issue by payet-s** [pasquim/apirate#7]
Concerning the issue #6, it doesn't appear in the UML diagram. In other word, the source code distributed doesn't match the UML diagram. I won't be surprised if it's the case for others methods as well.

Cordially,
payet-s

**Comment by pasquim** [comment]
Bonsoir, 

En effet, suite aux dernières modifications le diagramme UML n'avait pas été tenu à jour. Il est maintenant mis à jour et le sera si de nouvelles modifications sont faites.

Bonne soirée.
